CREATE DATABASE TASK_DB;
USE TASK_DB;
CREATE TABLE T_USER(
    USER_ID VARCHAR(12) NOT NULL PRIMARY KEY,
    USER_NM VARCHAR(10) NOT NULL,
    PASSWORD VARCHAR(8) NOT NULL,
    OFFICE_CD VARCHAR(4) NOT NULL,
    BIRTHDAY DATETIME,
    SENIORYTY INT(2),
    DELET_FLG VARCHAR(1) DEFAULT 0 NOT NULL
);