(1)
SELECT *
FROM T_USER
WHERE OFFICE_CD = '3001'
AND DELET_FLG = '0';
(2)
SELECT USER_ID, USER_NM
FROM T_USER
WHERE BIRTHDAY >= '2000'
AND DELET_FLG = '0';
(3)
SELECT COUNT(*)
FROM T_USER
WHERE USER_NM LIKE '%田%'
AND DELET_FLG = '0';
(4)
SELECT *
FROM T_USER
WHERE DELET_FLG = '0'
ORDER BY BIRTHDAY DESC;
(5)
SELECT USER_NM
FROM T_USER
WHERE BIRTHDAY = (
    SELECT MAX(BIRTHDAY)
    FROM T_USER
)
OR BIRTHDAY = (
    SELECT MIN(BIRTHDAY)
    FROM T_USER
)
AND DELET_FLG = '0';
(6)
SELECT USER_ID, USER_NM, PASSWORD, OFFICE_CD, IFNULL(BIRTHDAY, '2000-01-01'), IFNULL(SENIORYTY,'不明'), DELET_FLG
FROM T_USER
WHERE DELETE_FLG = '0';
(7)
SELECT TIMESTAMPDIFF(YEAR, BIRTHDAY, CURDATE())
FROM T_USER
WHERE DELET_FLG = '0';